### ISSUE TITLE
[linter]: unexpected `no-useless-insertvalue` behaviour

### ISSUE THREAD

**Issue by fedeci** [withfig/autocomplete-tools#49]
See https://discord.com/channels/837809111248535583/959871605025149018

```sh
kyleerhabor@Kyles-MBP fig-autocomplete % npm run lint

> @withfig/autocomplete@2.170.1 lint
> eslint '**/*.ts' && npx prettier --check '**/*.ts'


Oops! Something went wrong! :(

ESLint: 8.12.0

TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting /Users/kyleerhabor/Projects/GitHub/fig-autocomplete/src/clojure.ts:22
Rule: "@withfig/fig-linter/no-useless-insertvalue"
    at /Users/kyleerhabor/Projects/GitHub/fig-autocomplete/node_modules/@withfig/eslint-plugin-fig-linter/rules/no-useless-insertvalue.js:13:34
    at Array.find (<anonymous>)
    at Property (/Users/kyleerhabor/Projects/GitHub/fig-autocomplete/node_modules/@withfig/eslint-plugin-fig-linter/rules/no-useless-insertvalue.js:12:53)
    at ruleErrorHandler (/Users/kyleerhabor/Projects/GitHub/fig-autocomplete/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /Users/kyleerhabor/Projects/GitHub/fig-autocomplete/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/kyleerhabor/Projects/GitHub/fig-autocomplete/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/kyleerhabor/Projects/GitHub/fig-autocomplete/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/kyleerhabor/Projects/GitHub/fig-autocomplete/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/kyleerhabor/Projects/GitHub/fig-autocomplete/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```
```ts
/**
 * Create an option with aliasing support.
 *
 * @param option The option
 * @returns An option optimized for aliases
 */
function alias(option: Fig.Option): Fig.Option {
  let oName = singleName(option.name);

  return {
    ...option,
    name: `${oName}:`,
    displayName: `${oName}:&lt;aliases&gt;`,
    insertValue: `${oName}:{cursor}`,
  };
}
```

**Comment by fedeci** [comment]
Fixed in v1.1.1!
