### ISSUE TITLE
missing positional arg 'dest'

### ISSUE THREAD

**Issue by golaniy** [withfig/autocomplete-tools#87]
Hi team! Love fig.
Having a problem with the argparse integration:
```
Traceback (most recent call last):
  File "/Users/yotamg/bitbucket/pywiliot-deployment-tools/wiliot_deployment_tools/internal/test_tool/power_control_cli.py", line 58, in <module>
    main()
  File "/Users/yotamg/bitbucket/pywiliot-deployment-tools/wiliot_deployment_tools/internal/test_tool/power_control_cli.py", line 22, in main
    add_completion_spec_command(parser)
  File "/Users/yotamg/opt/anaconda3/envs/pywiliot_internal/lib/python3.8/site-packages/argparse_complete_fig/fig.py", line 206, in add_completion_spec_command
    parser.add_argument(action=GenerateFigSpecAction)
  File "/Users/yotamg/opt/anaconda3/envs/pywiliot_internal/lib/python3.8/argparse.py", line 1350, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
TypeError: _get_positional_kwargs() missing 1 required positional argument: 'dest'

```
This is running on macOS ventura, python 3.9.

Can you help?

**Comment by fedeci** [comment]
This should fix https://pypi.org/project/argparse-complete-fig/1.0.1/
